arko_core:
    resource: "@ArkoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

arko_user:
    resource: "@ArkoUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"